# fly.toml file generated for rough-resonance-1888 on 2022-12-20T13:06:26-08:00

app = "rough-resonance-1888"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  [build.args]
    BUILD_COMMAND = "bin/rails fly:build"
    SERVER_COMMAND = "bin/rails fly:server"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  LOCAL_DOMAIN = "rough-resonance-1888.fly.dev"
  WEB_CONCURRENCY = "0" # exactly 1 Puma process
  DB_USER = "postgres"
  DB_HOST = "rough-resonance-1888-db.internal"
  MALLOC_ARENA_MAX = "2"
  MAX_THREADS = "1"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  RAILS_SERVE_STATIC_FILES = "false"
  REDIS_HOST = "rough-resonance-1888-redis.internal"
  REDIS_PORT = "6379"

[processes]
  web = "bin/rails server -b [::] -p 8080"
  worker = "bundle exec sidekiq -c $MAX_THREADS"

[[services]]
  processes = ["web"]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    path = "/health"
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/opt/mastodon/public"
  url_prefix = "/"
