default:
  &defaults # Your push api key, it is possible to set this dynamically using ERB:
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"

  # Your app's name
  name: "<%= ENV['LOCAL_DOMAIN'] %>"

  # Actions that should not be monitored by AppSignal
  # ignore_actions:
  #   - ApplicationController#isup

  # Errors that should not be recorded by AppSignal
  # For more information see our docs:
  # https://docs.appsignal.com/ruby/configuration/ignore-errors.html
  # ignore_errors:
  #   - Exception
  #   - NoMemoryError
  #   - ScriptError
  #   - LoadError
  #   - NotImplementedError
  #   - SyntaxError
  #   - SecurityError
  #   - SignalException
  #   - Interrupt
  #   - SystemExit
  #   - SystemStackError

  # See https://docs.appsignal.com/ruby/configuration/options.html for
  # all configuration options.

  # Skip session data, if it contains private information. Default: false
  skip_session_data: true

  # Ignore these errors (Optional)
  ignore_errors:
    - SystemExit

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true

staging:
  <<: *defaults
  active: false

test: # Testing app environment
  <<: *defaults
  active: false
