name: Deploy To Staging
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.6
          bundler-cache: false
      - name: Deploy to Staging
        uses: miloserdow/capistrano-deploy@master
        with:
          target: staging
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
