name: Run Tests
on: [pull_request]
jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: docker-compose
        uses: isbang/compose-action@v1.4.1
      - name: run tests
        run: docker exec bundle exec rails rspec
