name: Run Tests
on: [pull_request]
jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    uses: ./build-image
    env:
      RAILS_ENV: test
    steps:
      - name: run tests
        run: bundle exec rspec
