env:
  POSTGRES_USER: postgres
  POSTGRES_HOST: localhost
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: mastodon_test

name: Rails tests

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/**"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.4
          bundler-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get install -y ffmpeg imagemagick libpam-dev
      - name: Run Rails tests
        run: |
          bin/rails assets:precompile
          bin/rails db:create db:schema:load db:seed
          bin/rails test:prepare test
